# General signage functions

from sevencourts import *

COLOR_BW_VAIHINGEN_ROHR_BLUE = graphics.Color(0x09, 0x65, 0xA6)  # #0965A6

COLOR_SIGNAGE_BG_TOURNAMENT_NAME = COLOR_BW_VAIHINGEN_ROHR_BLUE
COLOR_SIGNAGE_FG_TOURNAMENT_NAME = COLOR_WHITE

COLOR_SIGNAGE_FG_COURT_SEPARATOR_LINE = COLOR_GREY_DARK
COLOR_SIGNAGE_BG_COURT_NAME = COLOR_GREY
COLOR_SIGNAGE_FG_COURT_NAME = COLOR_BLACK

COLOR_SIGNAGE_FG_TEAM_NAME = COLOR_WHITE
COLOR_SIGNAGE_FG_SCORE = COLOR_GREY
COLOR_SIGNAGE_FG_SCORE_WON = COLOR_WHITE
COLOR_SIGNAGE_FG_SCORE_LOST = COLOR_GREY

def score_color(t1: int, t2: int, finished=True):
    if finished and t1 and t2:
        return [COLOR_SIGNAGE_FG_SCORE_WON if (t1 > t2) else COLOR_SIGNAGE_FG_SCORE_LOST,
                COLOR_SIGNAGE_FG_SCORE_WON if (t2 > t1) else COLOR_SIGNAGE_FG_SCORE_LOST]
    else:
        return [COLOR_SIGNAGE_FG_SCORE, COLOR_SIGNAGE_FG_SCORE]
